// web/components/Lobby.tsx
"use client";

/* PASO 1 — lobby (lista de jugadores, fichar, bots).
   El botón "Empezar partida" se agregó en el Paso 2. */

import { useGame } from "@/lib/game";

export function Lobby() {
  const {
    estado,
    miId,
    ficharEntrada,
    agregarBots,
    limpiarBots,
    expulsar,
    empezarPartida,
    salir,
  } = useGame();

  if (!estado) return null;

  const yo = estado.players.find((p) => p.id === miId);
  const listos = estado.players.filter((p) => p.ready).length;
  const total = estado.players.length;
  const hayBots = estado.players.some((p) => p.isBot);
  const soyHost = !!yo && yo.id === estado.hostId;
  const todosFichados = total > 0 && estado.players.every((p) => p.ready);
  const puedeEmpezar = total >= 2 && todosFichados;

  // Texto del botón "Empezar" según qué falta.
  let textoEmpezar = "EMPEZAR PARTIDA";
  if (total < 2) textoEmpezar = "Necesitás 2+ jugadores";
  else if (!todosFichados) textoEmpezar = `Faltan fichar (${listos}/${total})`;

  return (
    <div className="screen">
      <div className="topbar">
        <span className="brand">
          SINERGIA<span className="dot">·</span>CORP
        </span>
        <span className="pill">Sala {estado.code}</span>
      </div>
      <div className="appheader">Intranet · Lobby</div>

      <div className="content">
        <div className="codebox">
          <div className="lbl">CÓDIGO DE SALA</div>
          <div className="val">{estado.code}</div>
        </div>

        <h2>
          Plantilla {total} / 12 · {listos} fichados
        </h2>

        <div className="card pad0">
          {estado.players.map((p) => (
            <div
              key={p.id}
              className={"player" + (p.connected ? "" : " off")}
            >
              <div className="av">{p.avatar}</div>
              <span className="nm">
                {p.nickname}
                {p.id === miId && <span className="tag">vos</span>}
                {p.id === estado.hostId && (
                  <span className="tag">anfitrión</span>
                )}
                {p.isBot && <span className="tag bot">bot</span>}
              </span>
              <span className={"st" + (p.ready ? " ready" : "")}>
                {!p.connected
                  ? "desconectado"
                  : p.ready
                    ? "✓ fichado"
                    : "· sin fichar"}
              </span>
              {soyHost && p.id !== miId && (
                <button
                  className="kick"
                  title={`Expulsar a ${p.nickname}`}
                  onClick={() => expulsar(p.id)}
                >
                  ✕
                </button>
              )}
            </div>
          ))}
        </div>

        <div className="dev">
          <div className="devtitle">🧪 MODO DESARROLLO</div>
          <div className="devrow">
            <button className="btn ghost sm" onClick={() => agregarBots(1)}>
              + 1 bot
            </button>
            <button className="btn ghost sm" onClick={() => agregarBots(3)}>
              + 3 bots
            </button>
            <button
              className="btn ghost sm"
              onClick={limpiarBots}
              disabled={!hayBots}
            >
              Quitar bots
            </button>
          </div>
        </div>
      </div>

      <div className="actionbar">
        {soyHost ? (
          <button
            className="btn"
            disabled={!puedeEmpezar}
            onClick={empezarPartida}
          >
            {textoEmpezar}
          </button>
        ) : (
          <p className="muted-note">
            Esperando a que el anfitrión empiece la partida…
          </p>
        )}
        <div className="devrow">
          <button
            className="btn ghost sm"
            onClick={() => ficharEntrada(!yo?.ready)}
          >
            {yo?.ready ? "Cancelar fichaje" : "Fichar entrada"}
          </button>
          <button className="btn danger sm" onClick={salir}>
            Salir
          </button>
        </div>
      </div>
    </div>
  );
}

// web-angular/src/app/lobby/lobby.ts
import { Component, computed, inject } from '@angular/core';
import { GameService } from '../game.service';
import { Avatar } from '../avatar/avatar';
import { dlog } from '../dlog'; // TEMPORAL: logs de depuración

/**
 * Pantalla de Lobby: lista de jugadores en vivo, fichaje, bots de
 * desarrollo, expulsar jugadores y arrancar la partida.
 *
 * Todo el "estado calculado" (cuántos fichados, si soy anfitrión, etc.)
 * se arma con computed(): se recalcula solo cuando cambia el estado del
 * juego. El componente no guarda estado propio — solo deriva del server.
 */
@Component({
  selector: 'app-lobby',
  imports: [Avatar],
  templateUrl: './lobby.html',
})
export class Lobby {
  private readonly juego = inject(GameService);

  /** Mi sessionId, para marcar "vos" y ocultar mi botón de expulsar. */
  readonly miId = this.juego.miId;

  /*
   * El signal `estado` del servicio es StateView | null. Acá la app solo
   * rutea al Lobby cuando hay estado, pero TypeScript no lo sabe. Por eso
   * derivamos cada dato con computed() y un valor por defecto: nunca hay
   * que escribir `estado()!` y el código queda a prueba de null.
   */
  readonly code = computed(() => this.juego.estado()?.code ?? '');
  readonly hostId = computed(() => this.juego.estado()?.hostId ?? '');
  readonly jugadores = computed(() => this.juego.estado()?.players ?? []);

  /** Cuántos jugadores ficharon entrada. */
  readonly listos = computed(
    () => this.jugadores().filter((p) => p.ready).length,
  );
  /** Total de jugadores en la sala. */
  readonly total = computed(() => this.jugadores().length);
  /** ¿Hay algún bot? (para habilitar "Quitar bots"). */
  readonly hayBots = computed(() => this.jugadores().some((p) => p.isBot));
  /** Mi propio registro de jugador. */
  readonly yo = computed(() =>
    this.jugadores().find((p) => p.id === this.miId()),
  );
  /** ¿Soy el anfitrión? Solo el anfitrión puede empezar la partida. */
  readonly soyHost = computed(() => {
    const y = this.yo();
    return !!y && y.id === this.hostId();
  });
  /** ¿Ficharon todos? Es requisito para arrancar. */
  readonly todosFichados = computed(
    () => this.total() > 0 && this.jugadores().every((p) => p.ready),
  );
  /** ¿Se puede empezar? (2+ jugadores y todos fichados). */
  readonly puedeEmpezar = computed(
    () => this.total() >= 2 && this.todosFichados(),
  );
  /** Texto del botón de empezar, según qué falta. */
  readonly textoEmpezar = computed(() => {
    if (this.total() < 2) return 'Necesitás 2+ jugadores';
    if (!this.todosFichados()) {
      return `Faltan fichar (${this.listos()}/${this.total()})`;
    }
    return 'EMPEZAR PARTIDA';
  });

  /* ---------- acciones (delegan en el GameService) ---------- */

  /** Ficha o cancela el fichaje (invierte mi estado actual). */
  fichar(): void {
    const valor = !this.yo()?.ready;
    dlog('Lobby.fichar', { nuevoValor: valor });
    this.juego.ficharEntrada(valor);
  }

  agregarBots(n: number): void {
    dlog('Lobby.agregarBots', n);
    this.juego.agregarBots(n);
  }

  quitarBots(): void {
    dlog('Lobby.quitarBots');
    this.juego.limpiarBots();
  }

  expulsar(id: string): void {
    dlog('Lobby.expulsar', id);
    this.juego.expulsar(id);
  }

  empezar(): void {
    dlog('Lobby.empezar');
    this.juego.empezarPartida();
  }

  salir(): void {
    dlog('Lobby.salir');
    this.juego.salir();
  }
}
